---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(sqldf)
library(readxl)
library(rvest)
library(plotly)
library(flexdashboard)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r}
practice_data = read_excel("./data/Practice_exercise.xlsx", sheet = "Data") %>%
  janitor::clean_names() %>%
  select(observation_number,quarter,employee_id, sex = sex_male_1, race, age, hospital_visit = hospital_visit_this_quarter_1_yes, salary, health_score) %>%
  mutate(
    age_cat = case_when(
      age < 30 ~ 1,
      age <= 45 ~ 2,
      age > 45 ~ 3
    )
  )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
practice_data %>%
  drop_na() %>%
  select(quarter, race, health_score) %>%
  mutate(
    race = factor(race)
  ) %>%
  group_by(
    race, quarter
  ) %>%
  summarise(
    mean_score = round(mean(health_score)),1
  ) %>%
  plot_ly(
   x = ~quarter, y = ~ mean_score, color = ~race, type = "bar"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
practice_data %>%
  drop_na() %>%
  select(quarter, sex, health_score) %>%
  mutate(
    sex = factor(sex)
  ) %>%
  group_by(
    sex, quarter
  ) %>%
  summarise(
    mean_score = round(mean(health_score),1)
  ) %>%
  plot_ly(
   x = ~quarter, y = ~ mean_score, color = ~sex, type = "bar"
  )
```

### Chart C

```{r}
practice_data %>%
  drop_na() %>%
  select(quarter, sex, salary) %>%
  mutate(
    sex = factor(sex)
  ) %>%
  group_by(
    sex, quarter
  ) %>%
  summarise(
    mean_sal = round(mean(salary)),2
  ) %>%
  plot_ly(
   x = ~quarter, y = ~ mean_sal, color = ~sex, type = "bar"
  )
```

